-- Add up migration script here

ALTER TABLE `users` MODIFY `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users` MODIFY `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;